name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Java
      uses: actions/setup-java@v3.3.0
      with:
        distribution: "zulu"
        java-version: "17"
        java-package: jdk

    - name: Run SDK
      run: |
        chmod +x install.sh
        ./install.sh
